# Definir la URL base y las categorías
base_url = "https://www.disco.com.ar/"
categorias_deseadas = ["almacen/aceites-y-vinagres/aceites-comunes",
                       "almacen/aceites-y-vinagres/vinagres",
                       "almacen/arroz-y-legumbres/arroz",
                       "almacen/desayuno-y-merienda/galletitas-dulces",
                       "almacen/desayuno-y-merienda/galletitas-saladas",
                       "almacen/desayuno-y-merienda/yerbas",
                       "almacen/desayuno-y-merienda/cafes",
                       "almacen/arroz-y-legumbres/legumbres",
                       "almacen/sal-pimienta-y-especias/sal",
                       "almacen/aceites-y-vinagres/jugos-de-limon",
                       "almacen/conservas/conservas-de-verduras-y-legumbres",
                       "almacen/pastas-secas-y-salsas/pastas-secas-largas",
                       "almacen/harinas/harinas",
                       "almacen/desayuno-y-merienda/tes",
                       "almacen/desayuno-y-merienda/mermeladas-y-jaleas",
                       "almacen/desayuno-y-merienda/azucar-y-edulcorantes",
                       "almacen/panificados/lacteados",
                       "quesos-y-fiambres/dulces",
                       "quesos-y-fiambres/quesos/quesos-duros",
                       "quesos-y-fiambres/quesos/quesos-untables",
                       "frutas-y-verduras/huevos",
                       "lacteos/leches",
                       "lacteos/dulce-de-leche",
                       "bebidas/jugos/en-polvo",
                       "bebidas/aguas/aguas-con-gas",
                       "carnes/carne-vacuna",
                       "carnes/pollo"
                       "limpieza/desodorantes-de-ambiente/desodorantes-y-desinfectantes",
                       "limpieza/accesorios-de-limpieza/esponjas-y-guantes",
                       "limpieza/accesorios-de-limpieza/panos-multiusos",
                       "limpieza/accesorios-de-limpieza/trapos-de-piso",
                       "limpieza/lavandina",
                       "limpieza/cuidado-para-la-ropa/jabon-en-pan",
                       "limpieza/limpieza-de-cocina/detergentes",
                       "limpieza/limpieza-de-pisos-y-muebles/limpiadores-de-pisos",
                       "limpieza/papeles/papel-higienico",
                       "limpieza/cuidado-para-la-ropa/suavizantes",
                       "limpieza/cuidado-para-la-ropa/detergente-para-ropa",
                       "perfumeria/cuidado-capilar/acondicionador",
                       "perfumeria/cuidado-capilar/shampoo",
                       "perfumeria/cuidado-oral/cepillos-dentales",
                       "perfumeria/cuidado-oral/pastas-dentales",
                       "perfumeria/cuidado-personal/jabones",
                       "perfumeria/cuidado-personal/desodorantes-de-mujer",
                       "perfumeria/cuidado-personal/productos-para-afeitarse",
                       "perfumeria/cuidado-personal/proteccion-femenina"]

# Obtener los links de las categorías
links_categorias = [f"{base_url}{cat}" for cat in categorias_deseadas]
